const app=document.querySelector('#app');
const STORE='drogs-2027';
let current=null,currentType='bishop';

const baseQuestions=[
  {id:'intention',title:role=>`Do you wish to continue serving as a ${role} for the coming year?`,help:'If you intend to resign, select that option. The D.R.O.G.S Office will contact you privately.',type:'choice',options:['I wish to continue','I wish to resign','I need to discuss my position']},
  {id:'standing',title:()=>`How would you describe your present standing and readiness for this office?`,help:'Use the scale as an honest personal reflection. It is not an automatic score.',type:'scale'},
  {id:'oversight',title:()=>`Are you actively overseeing and caring for the people, ministry and leaders entrusted to you?`,help:'Consider supervision, pastoral care, standards, training and timely support.',type:'choice',options:['Yes, consistently','Partly — I need support','No']},
  {id:'doctrine',title:()=>`Are you in agreement with the church’s statement of faith, aims, vision and governing direction?`,help:'Please disclose any area that requires clarification.',type:'choice',options:['Yes','I need clarification','No']},
  {id:'training',title:()=>`Have you intentionally trained and developed leaders or successors during this annual cycle?`,help:'Ministry includes producing and strengthening other leaders.',type:'choice',options:['Yes, consistently','Somewhat','Not during this period']},
  {id:'councils',title:()=>`Have you worked faithfully through the appropriate councils and implemented their decisions?`,help:'This includes participation, accountability and follow-through.',type:'choice',options:['Yes','Mostly','I need to discuss this']},
  {id:'communication',title:()=>`Are you maintaining open communication, unity and healthy relationships with leaders above and below you?`,help:'Include any isolation, unresolved conflict or relationship requiring help in your disclosure.',type:'choice',options:['Yes','Some areas need attention','No']},
  {id:'stewardship',title:()=>`Are the administration, reporting, finances and property under your care handled responsibly?`,help:'This includes compliance with church procedures and applicable laws.',type:'choice',options:['Yes','There are matters to resolve','No']},
  {id:'integrity',title:()=>`Is there any matter of conduct, marriage, finance, authority or personal integrity that requires confidential review?`,help:'A request for help is treated as a disclosure for authorized review, not as an automatic decision.',type:'choice',options:['No matter to disclose','Yes — I request a confidential review']},
  {id:'commitment',title:()=>`Will you uphold the obligations of this office, including confidentiality, accountability and responsible leadership?`,help:'Your annual declaration confirms the information supplied in this submission.',type:'choice',options:['Yes, I recommit','I need to discuss this before recommitting']}
];

const roster=()=>currentType==='bishop'?BISHOPS:PASTORS;
const role=()=>currentType==='bishop'?'Leader':'Pastor';
const cycle=()=>currentType==='bishop'?'leadership':'pastoral';
const key=b=>`${currentType}:${b.code}`;
const initials=name=>name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const portrait=(person,className='',alt='')=>person.image?`<img class="${className}" src="${person.image}" alt="${esc(alt||person.name)}">`:`<span class="avatar ${className}" aria-label="${esc(alt||person.name)}">${initials(person.name)}</span>`;
const displayName=person=>`${person.honorific?`${person.honorific} `:''}${person.name}`;
const paymentApps=[
  ['Wise','https://wise.com/send-money'],['Sendwave','https://www.sendwave.com/en'],['Remitly','https://www.remitly.com/'],['Western Union','https://www.westernunion.com/'],['WorldRemit','https://www.worldremit.com/'],
  ['LemFi','https://www.lemfi.com/'],['Taptap Send','https://www.taptapsend.com/'],['MoMo','https://momo.mtn.com/'],['Skrill','https://www.skrill.com/'],['Paysend','https://paysend.com/'],
  ['TransferGo','https://www.transfergo.com/'],['PayAngel','https://payangel.com/'],['Chipper','https://www.chippercash.com/'],['Mukuru','https://www.mukuru.com/'],['Flutterwave','https://flutterwave.com/'],
  ['Telecel Cash','https://telecel.com.gh/personal/telecel-cash/'],['AT Money','https://at.com.gh/']
];
const paymentAppLinks=()=>paymentApps.map(([name,url])=>`<a class="payment-app" href="${url}" target="_blank" rel="noopener noreferrer" aria-label="Open ${name}"><span>${name}</span><i>↗</i></a>`).join('');

function loadRecords(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}}
function saveRecords(records){localStorage.setItem(STORE,JSON.stringify(records));window.dispatchEvent(new Event('storage'))}
function seeded(b){let status='not_started',paid=false,review='Awaiting submission';if(b.code%19===0){status='submitted';review='Ready for review'}if(b.code%31===0){status='submitted';paid=true;review='In review'}if(b.code%47===0){status='submitted';paid=true;review='Approved'}return{status,paid,review,updatedAt:null,responses:{},paymentMethod:null}}
function record(b){return loadRecords()[key(b)]||seeded(b)}
function put(b,patch){const all=loadRecords();all[key(b)]={...record(b),...patch,role:currentType};saveRecords(all)}

function route(){const hash=location.hash.slice(1);if(hash==='declaration'&&current)return declaration();if(hash==='payment'&&current)return payment();if(hash==='receipt'&&current)return receipt();if(hash==='profile'&&current)return profile();home()}
function home(){
  current=null;
  app.innerHTML=`<section class="hero"><div class="hero-grid"></div><div class="hero-content"><div class="eyebrow">D.R.O.G.S · 2027</div><div class="role-switch" role="group" aria-label="Choose record type"><button data-role="bishop" class="${currentType==='bishop'?'active':''}">Bishops <small>${BISHOPS.length}</small></button><button data-role="pastor" class="${currentType==='pastor'?'active':''}">Pastors <small>${PASTORS.length.toLocaleString()}</small></button></div><h1>Confirm your<br><em>commitment.</em></h1><p>Enter your private access code to open your annual record, confirm your commitment and follow its progress.</p><form class="access-card" id="access"><input id="code" inputmode="numeric" pattern="[0-9]*" placeholder="Enter your private code" aria-label="Private access code" autocomplete="one-time-code"><button>Continue <span>→</span></button></form><div class="error" id="access-error" role="alert"></div></div></section>`;
  document.querySelectorAll('[data-role]').forEach(button=>button.onclick=()=>{currentType=button.dataset.role;home()});
  document.querySelector('#access').onsubmit=event=>{event.preventDefault();const code=Number(document.querySelector('#code').value);current=roster().find(person=>person.code===code);if(!current){document.querySelector('#access-error').textContent='We could not find that private code. Check it and try again.';return}if(location.hash==='#profile')profile();else location.hash='profile'};
}
function statusCopy(r){return{application:r.status==='submitted'?'Submitted':r.status==='draft'?'Draft saved':'Not started',payment:r.paid?'Paid':'Outstanding',review:r.review||'Awaiting submission'}}
function profile(){
  const r=record(current),s=statusCopy(r);
  app.innerHTML=`<div class="wrap"><div class="topline"><div><div class="eyebrow">Your annual record</div><h1>Welcome, ${esc(displayName(current))}.</h1></div><button class="ghost" id="change">Use another code</button></div><section class="identity"><div class="portrait-panel">${portrait(current,'profile-portrait')}</div><div class="identity-copy"><h2>${esc(displayName(current))}</h2>${current.designation?`<div class="designation">${esc(current.designation)}</div>`:''}<p>Submit your annual declaration and confirm the annual fee. The D.R.O.G.S Office will review your submission and update the decision here.</p><div class="status-rail"><div><span>Application</span><b>${s.application}</b></div><div><span>Annual fee</span><b>${s.payment}</b></div><div><span>Church review</span><b>${s.review}</b></div></div>${r.status==='submitted'?`<button class="primary large" id="continue">${r.paid?'View receipt':'Continue to payment'} <span>→</span></button>`:`<button class="primary large" id="continue">Fill annual declaration <span>→</span></button>`}</div></section></div>`;
  document.querySelector('#change').onclick=()=>{location.hash='home'};
  document.querySelector('#continue').onclick=()=>{location.hash=r.status==='submitted'?(r.paid?'receipt':'payment'):'declaration'};
}
function qHtml(q,i,value,responses={}){
  const title=q.title(role().toLowerCase());
  if(q.type==='scale')return`<div class="question"><span class="qno">${String(i+1).padStart(2,'0')}</span><h3>${title}</h3><p>${q.help}</p><div class="scale">${[1,2,3,4,5,6,7,8,9,10].map(n=>`<label>${n}<input type="radio" name="${q.id}" value="${n}" ${String(value)===String(n)?'checked':''}></label>`).join('')}</div></div>`;
  return`<div class="question"><span class="qno">${String(i+1).padStart(2,'0')}</span><h3>${title}</h3><p>${q.help}</p><div class="options">${q.options.map(o=>`<label><input type="radio" name="${q.id}" value="${esc(o)}" ${value===o?'checked':''}> ${esc(o)}</label>`).join('')}</div>${q.id==='intention'?`<textarea class="field" name="intentionNote" placeholder="If you wish to resign or discuss your position, tell the D.R.O.G.S Office what you would like them to know.">${esc(responses.intentionNote||'')}</textarea>`:''}</div>`
}
function declaration(){
  const r=record(current),answered=baseQuestions.filter(q=>r.responses?.[q.id]).length;
  app.innerHTML=`<div class="wrap"><div class="topline"><div><div class="eyebrow">Annual declaration</div><h1>Your annual declaration</h1><p>Answer the questions that apply. You can save the form and return before submitting.</p></div><button class="ghost" id="back">Back to profile</button></div><div class="form-shell"><aside class="form-aside"><div class="mini-person">${portrait(current,'mini-avatar')}<div><strong>${esc(displayName(current))}</strong><small>${role()} code ${current.code}</small></div></div><div class="progress"><i style="width:${answered/10*100}%"></i></div><div class="progress-copy">${answered} of 10 governance questions answered</div></aside><form class="content-card" id="declaration-form">${baseQuestions.map((q,i)=>qHtml(q,i,r.responses?.[q.id],r.responses)).join('')}<div class="question"><span class="qno">CONFIDENTIAL DISCLOSURE</span><h3>Is there anything else the D.R.O.G.S Office or reviewing council should know?</h3><p>Use this space to request support, clarify an answer, or disclose a matter for private review.</p><textarea class="field" name="disclosure" placeholder="Write your confidential note here">${esc(r.responses?.disclosure||'')}</textarea></div><div class="question"><label class="options"><span><input type="checkbox" name="declaration" ${r.responses?.declaration?'checked':''}> I confirm that these answers are complete and truthful to the best of my knowledge.</span></label></div><div class="form-actions"><p>You can continue with unanswered questions for now. Submitting sends this declaration to the D.R.O.G.S Office.</p><button class="primary">Continue to payment <span>→</span></button></div></form></div></div>`;
  document.querySelector('#back').onclick=()=>location.hash='profile';
  document.querySelector('#declaration-form').onchange=event=>{const fd=new FormData(event.currentTarget),responses=Object.fromEntries(fd.entries());responses.declaration=fd.has('declaration');put(current,{status:'draft',responses,updatedAt:new Date().toISOString()})};
  document.querySelector('#declaration-form').onsubmit=event=>{event.preventDefault();const fd=new FormData(event.currentTarget),responses=Object.fromEntries(fd.entries());responses.declaration=fd.has('declaration');put(current,{status:'submitted',responses,submittedAt:new Date().toISOString(),updatedAt:new Date().toISOString(),review:'Ready for review'});location.hash='payment'};
}
function payment(){
  const r=record(current);
  app.innerHTML=`<div class="wrap"><div class="topline"><div><div class="eyebrow">Annual commitment fee</div><h1>Complete your annual commitment.</h1><p>Your signed application has been submitted. Select how you would like to pay.</p></div><button class="ghost" id="back">Back to profile</button></div><div class="payment-grid"><section class="content-card"><div class="mini-person">${portrait(current,'mini-avatar')}<div><strong>${esc(displayName(current))}</strong><small>2027 annual commitment</small></div></div><div style="margin-top:30px"><label class="method"><input type="radio" name="method" value="Mobile Money" checked> <b>Ghana mobile money</b><span>Pay through the church’s Ghana mobile money route.</span></label><label class="method"><input type="radio" name="method" value="Card"> <b>Debit or credit card</b><span>Pay securely by card from outside Ghana.</span></label><label class="method"><input type="radio" name="method" value="Bank transfer"> <b>Bank transfer</b><span>Receive transfer instructions and a payment reference.</span></label></div><section class="transfer-apps"><div class="transfer-heading"><div><div class="eyebrow">Give through mobile apps</div><h2>053 042 9589 <small>MTN</small></h2></div><button type="button" id="copy-number">Copy number</button></div><p>Choose an app below, select Ghana and MTN, then enter the number above.</p><div class="payment-app-grid">${paymentAppLinks()}</div></section><button class="primary large" id="pay" style="margin-top:22px">I have paid — continue <span>→</span></button></section><aside class="amount-box"><div class="eyebrow" style="color:#9fb6b9">2027 annual commitment</div><strong>$${current.amount}</strong><small>Annual commitment fee</small><div class="status-rail" style="grid-template-columns:1fr;margin-top:32px;border-color:#ffffff22"><div style="border:0"><span style="color:#9fb6b9">Application</span><b>Submitted</b></div></div></aside></div></div>`;
  document.querySelector('#back').onclick=()=>location.hash='profile';
  document.querySelector('#copy-number').onclick=async event=>{await navigator.clipboard.writeText('0530429589');event.currentTarget.textContent='Copied'};
  document.querySelector('#pay').onclick=()=>{const method=document.querySelector('input[name=method]:checked').value;put(current,{paid:true,paymentMethod:method,paidAt:new Date().toISOString(),updatedAt:new Date().toISOString(),review:r.review==='Approved'?'Approved':'In review',receipt:`DRG-${currentType==='bishop'?'B':'P'}-2027-${String(current.code).padStart(4,'0')}`});location.hash='receipt'};
}
function receipt(){
  const r=record(current),date=new Date(r.paidAt||Date.now()).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'});
  app.innerHTML=`<div class="wrap"><section class="content-card receipt"><div class="receipt-head"><div class="success-mark">✓</div><img class="receipt-logo" src="assets/mitre-transparent.png" alt="D.R.O.G.S"><div class="eyebrow">Annual commitment receipt</div><h1 style="font-size:42px;letter-spacing:-2px;margin:10px 0">Thank you for completing your annual commitment.</h1></div><div class="receipt-person">${portrait(current,'receipt-avatar')}<div><h2>${esc(displayName(current))}</h2><p>2027 annual commitment</p></div></div><div class="receipt-lines"><div><span>Receipt number</span><b>${esc(r.receipt||`DRG-${currentType==='bishop'?'B':'P'}-2027-${String(current.code).padStart(4,'0')}`)}</b></div><div><span>Commitment year</span><b>2027</b></div><div><span>Amount paid</span><b>$${current.amount} USD</b></div><div><span>Payment method</span><b>${esc(r.paymentMethod||'Payment received')}</b></div><div><span>Date</span><b>${date}</b></div><div><span>Church review</span><b>${esc(r.review)}</b></div></div><div class="receipt-actions"><button class="primary" onclick="window.print()">Print receipt</button><button class="ghost" id="profile">Return to record</button></div></section></div>`;
  document.querySelector('#profile').onclick=()=>location.hash='profile';
}
function esc(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
window.addEventListener('hashchange',route);
route();
