import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PATH||'/Users/joshuagbafa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.js');
const base=process.env.DROGS_BASE_URL||'http://127.0.0.1:4199/drogs';
const c={window:{}};for(const n of ['bishop','pastor'])vm.runInNewContext(fs.readFileSync(new URL(`../data/${n}-questions.js`,import.meta.url),'utf8'),c);
const answers=qs=>{const r={};for(const q of qs){r[q.id]=q.review?.clear[0]||(q.type==='number'?'0':q.type==='text'?'Growing congregations and developing leaders.':'Yes');for(const f of q.followUps||[])if(!f.when||f.when===r[q.id])r[f.id]=f.review?.clear[0]||(f.type==='choice'?f.options[0]:'')}return r};
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const ctx=await browser.newContext(),errors=[];ctx.on('page',p=>p.on('pageerror',e=>errors.push(String(e))));
async function open(code){const p=await ctx.newPage();await p.goto(base);await p.locator('#entry-code, #code').first().waitFor();if(await p.locator('#entry-code').count()){await p.locator('#entry-code').fill('1234');await p.locator('#entry button').click()}await p.locator('#code').fill(code);await p.locator('#access button').click();await p.locator('#continue').click();await p.locator('#declaration-form').waitFor();return p}
async function fill(p,r){await p.evaluate(r=>{const f=document.querySelector('#declaration-form');for(const [k,v]of Object.entries(r)){const els=f.querySelectorAll(`[name="${k}"]`);for(const el of els){if(el.type==='radio')el.checked=el.value===v;else el.value=v}}f.dispatchEvent(new Event('change',{bubbles:true}))},r)}
async function review(p){await p.locator('#submit-declaration').click();await p.locator('#confirm-application').waitFor();assert.equal(await p.locator('#truthfulness').isChecked(),false)}
try{
 const p=await open('P1');await fill(p,answers(c.window.PASTOR_QUESTIONS));await p.locator('#save-declaration').click();assert.match(await p.locator('#draft-status').textContent(),/saved/);await review(p);
 assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('drogs-2027'))['pastor:1'].status),'draft');
 await p.locator('#confirm-submit').click();assert.equal(new URL(p.url()).hash,'#review');
 await p.locator('#edit-application').click();await p.locator('#declaration-form').waitFor();assert(await p.locator('[name="pastorBeliefs"][value="Yes"]').isChecked());await review(p);await p.locator('#truthfulness').check();await p.locator('#confirm-submit').click();await p.locator('#pay').waitFor();assert.equal(new URL(p.url()).hash,'#payment');
 const flagged=await open('P2');const responses={...answers(c.window.PASTOR_QUESTIONS),healthImpact:'Some impact — I have struggled or missed some duties',healthDetails:'I missed services and would like support.'};await fill(flagged,responses);await review(flagged);await flagged.locator('#truthfulness').check();await flagged.locator('#confirm-submit').click();await flagged.locator('#check-approval').waitFor();assert.equal(await flagged.locator('#pay').count(),0);await flagged.evaluate(()=>location.hash='payment');await flagged.locator('#check-approval').waitFor();assert.equal(await flagged.locator('#pay').count(),0);
 const admin=await ctx.newPage();await admin.goto(base+'/admin/');await admin.locator('#pin').fill('1234');await admin.locator('#login button').click();await admin.locator('[data-role="pastor"]').click();assert.equal(await admin.locator('.review-metric strong').textContent(),'1');await admin.locator('[data-review-queue]').click();assert.equal(await admin.locator('[data-submission-code]').count(),1);await admin.locator('[data-submission-code="2"]').click();assert.equal(await admin.locator('.fact-grid').count(),0);assert.equal(await admin.locator('#decision').count(),0);assert.match(await admin.locator('.flagged-content').textContent(),/I missed services/);assert(!await admin.locator('.flagged-content').textContent().then(x=>x.includes('Preferred payment')));
 fs.mkdirSync('/tmp/drogs-qa',{recursive:true});await admin.screenshot({path:'/tmp/drogs-qa/flagged-application.png',fullPage:true});await admin.locator('[data-review-action="Approved"]').click();assert.equal(await admin.locator('[data-submission-code]').count(),0);await flagged.locator('#pay, #approval-payment').first().waitFor();if(await flagged.locator('#approval-payment').count())await flagged.locator('#approval-payment').click();await flagged.locator('#pay').waitFor();
 await admin.locator('#submission-readiness').selectOption('reviewed');assert.equal(await admin.locator('[data-submission-code]').count(),1);
 const bishop=await open('B1');await fill(bishop,answers(c.window.BISHOP_QUESTIONS));await review(bishop);await bishop.locator('#truthfulness').check();await bishop.locator('#confirm-submit').click();await bishop.locator('#pay').waitFor();
 const resign=await open('P3');await fill(resign,{...answers(c.window.PASTOR_QUESTIONS),intention:'I wish to resign'});await review(resign);await resign.locator('#truthfulness').check();await resign.locator('#confirm-submit').click();await resign.locator('.confirmation-card').waitFor();await resign.waitForFunction(()=>location.hash==='#response');assert.equal(await resign.locator('#pay').count(),0);
 const alias=await open('B335');assert(await alias.locator('[name="pastorBeliefs"]').count());assert.match(await alias.locator('.mini-person').textContent(),/Joshua Gbafa/);
 await alias.setViewportSize({width:390,height:844});await fill(alias,answers(c.window.PASTOR_QUESTIONS));await review(alias);const save=await alias.locator('#save-reviewed').boundingBox(),submit=await alias.locator('#confirm-submit').boundingBox();assert(save.x+save.width<=submit.x);assert(Math.abs(save.y-submit.y)<10);await alias.locator('#confirm-submit').scrollIntoViewIfNeeded();await alias.screenshot({path:'/tmp/drogs-qa/review-mobile.png'});assert(await alias.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert.deepEqual(errors,[]);console.log('PASS: Save/review/edit/attestation, automatic approval for both roles, health flag + payment guard, focused admin queue + manual unlock, resignation, moved code alias, mobile review.');
}finally{await browser.close()}
