import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { createRequire } from 'node:module';

const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const BASE='http://127.0.0.1:4198';
const OUT='/tmp/drogs-qa';
await mkdir(OUT,{recursive:true});

const launchOptions={headless:true};
if(process.env.PLAYWRIGHT_EXECUTABLE_PATH)launchOptions.executablePath=process.env.PLAYWRIGHT_EXECUTABLE_PATH;
const browser=await chromium.launch(launchOptions);
const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});
const errors=[];
const watch=page=>{page.on('console',msg=>{if(msg.type()==='error')errors.push(`console: ${msg.text()}`)});page.on('pageerror',error=>errors.push(`page: ${error}`))};

const page=await context.newPage();
watch(page);
await page.goto(BASE,{waitUntil:'networkidle'});
await page.evaluate(()=>localStorage.clear());
await page.reload({waitUntil:'networkidle'});
assert(await page.getByRole('heading',{name:'Confirm your commitment.'}).isVisible());
assert.equal(await page.locator('body').textContent().then(x=>new RegExp(['rene','wal'].join(''),'i').test(x)),false);
assert.equal(await page.locator('[data-role="bishop"] small').textContent(),'193');
assert.equal(await page.evaluate(()=>document.documentElement.dataset.captureProtection),'active');

await page.locator('#code').fill('999');
await page.getByRole('button',{name:'Continue'}).click();
assert((await page.locator('#access-error').textContent()).includes('could not find'));
await page.locator('#code').fill('4');
await page.getByRole('button',{name:'Continue'}).click();
assert((await page.locator('.topline h1').textContent()).includes('Mother Adelaide Heward-Mills'));
assert.equal(await page.locator('.identity-copy h2').textContent(),'Mother Adelaide Heward-Mills');
assert.equal(await page.locator('.designation').textContent(),'UO-FLC190');
assert.equal(/International|code 4/i.test(await page.locator('.identity').textContent()),false);
await page.screenshot({path:`${OUT}/public-profile.png`,fullPage:true});

await page.getByRole('button',{name:/Fill annual declaration/}).click();
await page.getByRole('heading',{name:'Your annual declaration'}).waitFor();
await page.getByRole('button',{name:/Continue to payment/}).click();
await page.getByRole('heading',{name:'Complete your annual commitment.'}).waitFor();
assert.equal(await page.locator('.payment-app').count(),17);
assert.equal(await page.getByRole('link',{name:'Open Wise'}).getAttribute('href'),'https://wise.com/send-money');
assert((await page.locator('.transfer-heading h2').textContent()).includes('053 042 9589'));
await page.screenshot({path:`${OUT}/payment-apps.png`,fullPage:true});
await page.getByRole('button',{name:/I have paid/}).click();
await page.getByText('Thank you for completing your annual commitment.').waitFor();
assert(await page.getByText('DRG-B-2027-0004').isVisible());
const logoFit=await page.locator('.receipt-logo').evaluate(el=>({fit:getComputedStyle(el).objectFit,w:el.clientWidth,h:el.clientHeight,nw:el.naturalWidth,nh:el.naturalHeight}));
assert.equal(logoFit.fit,'contain');
assert(logoFit.w>0&&logoFit.h>0&&logoFit.nw>0&&logoFit.nh>0);
await page.screenshot({path:`${OUT}/receipt.png`,fullPage:true});

const admin=await context.newPage();
watch(admin);
await admin.goto(`${BASE}/admin/`,{waitUntil:'networkidle'});
assert.equal(await admin.evaluate(()=>document.documentElement.dataset.captureProtection),'active');
await admin.locator('#pin').fill('1111');
await admin.getByRole('button',{name:'Enter D.R.O.G.S Office'}).click();
assert((await admin.locator('#error').textContent()).includes('not correct'));
await admin.locator('#pin').fill('1234');
await admin.getByRole('button',{name:'Enter D.R.O.G.S Office'}).click();
assert(await admin.getByRole('heading',{name:'D.R.O.G.S Office'}).isVisible());
assert.equal(await admin.locator('tbody tr').count(),193);
await admin.locator('#search').fill('Adelaide Heward-Mills');
assert.equal(await admin.locator('tbody tr').count(),1);
assert((await admin.locator('tbody tr').textContent()).includes('Mother Adelaide Heward-Mills'));
await admin.locator('tbody tr').click();
assert(await admin.getByRole('heading',{name:'Mother Adelaide Heward-Mills'}).isVisible());
await admin.locator('#close').click();
await admin.locator('#search').fill('');
await admin.locator('#view').click();
assert(await admin.locator('.bishop-card').first().isVisible());
await admin.screenshot({path:`${OUT}/admin-directory.png`,fullPage:true});
await admin.locator('[data-role="pastor"]').click();
assert.equal(await admin.locator('tbody tr').count(),4505);
await admin.locator('#search').fill('Aaron Boison');
assert.equal(await admin.locator('tbody tr').count(),1);

const privacy=await context.newPage();
watch(privacy);
await privacy.goto(BASE,{waitUntil:'networkidle'});
assert(await privacy.evaluate(()=>{const event=new Event('contextmenu',{bubbles:true,cancelable:true});return !document.dispatchEvent(event)}));
await privacy.evaluate(()=>window.dispatchEvent(new Event('blur')));
assert(await privacy.locator('body').evaluate(el=>el.classList.contains('privacy-hidden')));
await privacy.evaluate(()=>window.dispatchEvent(new Event('focus')));
await privacy.waitForTimeout(350);
assert.equal(await privacy.locator('body').evaluate(el=>el.classList.contains('privacy-hidden')),false);

const mobile=await context.newPage();
watch(mobile);
await mobile.setViewportSize({width:390,height:844});
await mobile.goto(BASE,{waitUntil:'networkidle'});
assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
await mobile.screenshot({path:`${OUT}/mobile-home.png`,fullPage:true});

assert.equal(errors.length,0,errors.join('\n'));
console.log('Browser QA passed: roster mapping, optional declaration, payment apps, receipt logo, admin dashboard, privacy controls, and mobile layout.');
console.log(OUT);
await browser.close();
