import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { createRequire } from 'node:module';

const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const BASE='http://127.0.0.1:4198';
const OUT='/tmp/drogs-qa';
await mkdir(OUT,{recursive:true});

const launchOptions={headless:true};
if(process.env.PLAYWRIGHT_EXECUTABLE_PATH)launchOptions.executablePath=process.env.PLAYWRIGHT_EXECUTABLE_PATH;
const browser=await chromium.launch(launchOptions);
const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});
const errors=[];
const watch=page=>{page.on('console',msg=>{if(msg.type()==='error')errors.push(`console: ${msg.text()}`)});page.on('pageerror',error=>errors.push(`page: ${error}`))};
const enterPortal=async page=>{await page.locator('#entry-code').fill('1234');await page.getByRole('button',{name:'Enter'}).click();await page.locator('#code').waitFor()};

const page=await context.newPage();
watch(page);
await page.goto(BASE,{waitUntil:'networkidle'});
await page.evaluate(()=>{localStorage.clear();sessionStorage.clear()});
await page.reload({waitUntil:'networkidle'});
assert(await page.getByRole('heading',{name:'D.R.O.G.S'}).isVisible());
assert.equal(await page.locator('[data-role]').count(),0);
assert.equal(await page.locator('.privacy-shield').count(),0);
await page.locator('#entry-code').fill('1111');
await page.getByRole('button',{name:'Enter'}).click();
assert((await page.locator('#entry-error').textContent()).includes('not correct'));
await enterPortal(page);
assert.equal(await page.locator('[data-role]').count(),0);
assert.equal(await page.locator('#code').getAttribute('placeholder'),'Enter your code here');
assert.equal(await page.locator('.hero p, .hero .eyebrow').count(),0);
assert.equal(await page.locator('body').textContent().then(x=>new RegExp(['rene','wal'].join(''),'i').test(x)),false);
assert.equal(await page.evaluate(()=>document.documentElement.dataset.captureProtection),'limited');

await page.locator('#code').fill('B999');
await page.getByRole('button',{name:'Continue'}).click();
assert((await page.locator('#access-error').textContent()).includes('could not find'));
await page.locator('#code').fill('B4');
await page.getByRole('button',{name:'Continue'}).click();
assert((await page.locator('.topline h1').textContent()).includes('Adelaide Heward-Mills'));
assert.equal(await page.locator('.identity-copy h2').textContent(),'Adelaide Heward-Mills');
assert((await page.locator('.affiliation').textContent()).includes('UD-OLGC'));
assert.equal(await page.locator('.profile-title').textContent(),'Episcopal Sister');
assert(await page.locator('.profile-portrait').getAttribute('src'));
assert.equal(await page.locator('.portrait-watermark').count(),0);
assert.equal(await page.locator('.organization-name').textContent(),'UD-OLGC');
assert.equal(await page.locator('.denomination-name').textContent(),'QODESH CITY CHURCHES');
assert.equal(/International|code 4/i.test(await page.locator('.identity').textContent()),false);
await page.screenshot({path:`${OUT}/public-profile.png`,fullPage:true});

await page.goBack();
await page.locator('#code').waitFor();
assert.equal(await page.locator('.privacy-shield').count(),0);
assert.equal(await page.locator('body').evaluate(el=>el.classList.contains('privacy-hidden')),false);
await page.goForward();
await page.locator('.identity').waitFor();

await page.getByRole('button',{name:/Fill annual declaration/}).click();
await page.getByRole('heading',{name:'Your annual declaration'}).waitFor();
await page.getByRole('button',{name:/Continue to payment/}).click();
await page.getByRole('heading',{name:'Complete your annual commitment.'}).waitFor();
assert.equal(await page.locator('.payment-app').count(),17);
assert.equal(await page.getByRole('link',{name:'Open Wise'}).getAttribute('href'),'https://wise.com/send-money');
assert((await page.locator('.transfer-heading h2').textContent()).includes('053 042 9589'));
await page.getByRole('button',{name:/Submit payment proof/}).click();
assert((await page.locator('#proof-error').textContent()).includes('Upload'));
await page.locator('#proof').setInputFiles('/Users/joshuagbafa/Documents/Codex/pastoral-renewal/assets/mitre-transparent.png');
await page.locator('#proof-preview.ready').waitFor();
await page.screenshot({path:`${OUT}/payment-proof.png`,fullPage:true});
await page.getByRole('button',{name:/Submit payment proof/}).click();
await page.getByText('Thank you for completing your annual commitment.').waitFor();
assert(await page.getByText('DRG-B-2027-0004').isVisible());
const logoFit=await page.locator('.receipt-logo').evaluate(el=>({fit:getComputedStyle(el).objectFit,w:el.clientWidth,h:el.clientHeight,nw:el.naturalWidth,nh:el.naturalHeight}));
assert.equal(logoFit.fit,'contain');
assert(logoFit.w>0&&logoFit.h>0&&logoFit.nw>0&&logoFit.nh>0);
await page.screenshot({path:`${OUT}/receipt.png`,fullPage:true});

await page.getByRole('button',{name:'Return to record'}).click();
await page.getByRole('button',{name:'Sign out',exact:true}).click();
await page.locator('#entry-code').waitFor();
await page.goBack();
assert(await page.locator('#entry-code').isVisible());
await enterPortal(page);

await page.locator('#code').fill('P1');
await page.getByRole('button',{name:'Continue'}).click();
assert((await page.locator('.topline h1').textContent()).includes('Aaron Boison'));
assert((await page.locator('.affiliation').textContent()).includes('UD-OLGC'));
assert.equal(await page.locator('.denomination-logo').count(),1);
await page.screenshot({path:`${OUT}/pastor-profile.png`,fullPage:true});

const admin=await context.newPage();
watch(admin);
await admin.goto(`${BASE}/admin/`,{waitUntil:'networkidle'});
assert.equal(await admin.evaluate(()=>document.documentElement.dataset.captureProtection),'limited');
await admin.locator('#pin').fill('1111');
await admin.getByRole('button',{name:'Enter D.R.O.G.S Office'}).click();
assert((await admin.locator('#error').textContent()).includes('not correct'));
await admin.locator('#pin').fill('1234');
await admin.getByRole('button',{name:'Enter D.R.O.G.S Office'}).click();
assert(await admin.getByRole('heading',{name:'D.R.O.G.S Office'}).isVisible());

assert.equal(await admin.locator('.portrait-card').count(),await admin.evaluate(()=>BISHOPS.length));
assert.equal(await admin.locator('#sort').count(),0);
assert.equal(await admin.locator('.card-logo').count(),0);
assert.equal(await admin.locator('.card-photo').first().evaluate(img=>getComputedStyle(img).objectFit),'contain');
assert.equal(await admin.locator('.metric[data-filter="paid"] strong').textContent(),'1');
await admin.locator('#search').pressSequentially('Adelaide');
assert.equal(await admin.locator('#search').inputValue(),'Adelaide');
assert.equal(await admin.locator('.portrait-card').count(),1);
await admin.locator('.portrait-card').click();
assert(await admin.locator('.record-modal').isVisible());
assert.equal(await admin.locator('.record-title h2').textContent(),'Adelaide Heward-Mills');
assert.equal(await admin.locator('.record-person-title').textContent(),'Episcopal Sister');
assert(await admin.locator('.admin-proof img').isVisible());
await admin.keyboard.press('Escape');
await admin.locator('#search').fill('Kiki');
await admin.locator('.portrait-card').click();
await admin.locator('.record-logo').evaluate(img=>img.decode());
assert(await admin.locator('.record-photo').getAttribute('src'));
assert.equal(await admin.locator('.record-photo').evaluate(img=>getComputedStyle(img).objectFit),'contain');
assert.equal(await admin.locator('.record-organization').textContent(),'UO-FLC190');
await admin.screenshot({path:OUT+'/admin-record.png'});
await admin.locator('#browse-denomination').click();
assert.equal(await admin.locator('.record-modal').count(),0);
assert(await admin.locator('.portrait-card').count()>0);
await admin.locator('#clear-filters').click();
await admin.getByRole('button',{name:'Organization',exact:true}).click();
await admin.locator('[data-option="UD-OLGC"]').check();
const udCount=await admin.locator('.portrait-card').count();
assert.equal(udCount,await admin.evaluate(()=>BISHOPS.filter(p=>p.organization==='UD-OLGC').length));
await admin.locator('[data-option="UO-FLC190"]').check();
assert.equal(await admin.locator('.portrait-card').count(),await admin.evaluate(()=>BISHOPS.length));
await admin.locator('#done-filter').click();
await admin.locator('#clear-filters').click();
await admin.getByRole('button',{name:'Hide sidebar',exact:true}).click();
assert(await admin.locator('.shell').evaluate(el=>el.classList.contains('sidebar-collapsed')));
await admin.getByRole('button',{name:'Show sidebar',exact:true}).click();
assert((await admin.locator('.organization-counts').textContent()).includes('UD:'));
await admin.getByRole('button',{name:'Groups',exact:true}).click();
await admin.locator('[data-option="UI — United Islands"]').check();
assert(await admin.locator('.portrait-card').count()>0);
await admin.locator('#done-filter').click();
await admin.locator('#clear-filters').click();
await admin.screenshot({path:OUT+'/admin-directory.png'});
await admin.getByRole('button',{name:'List view',exact:true}).click();
assert.equal(await admin.locator('tbody tr').count(),await admin.evaluate(()=>BISHOPS.length));
assert(await admin.getByRole('columnheader',{name:'Title',exact:true}).isVisible());
assert(await admin.getByRole('columnheader',{name:'Country',exact:true}).isVisible());
assert.equal(await admin.getByRole('columnheader',{name:'Country / branch'}).count(),0);
await admin.locator('[data-role="pastor"]').click();
assert((await admin.locator('tbody tr').count())>5000);
await admin.getByRole('button',{name:'Groups',exact:true}).click();
await admin.locator('[data-option="FL OJ: ONLY JESUS"]').check();
assert(await admin.locator('tbody tr').count()>0);
await admin.locator('#done-filter').click();
await admin.locator('tbody tr').first().click();
assert((await admin.locator('.fact-grid').textContent()).includes('FL OJ: ONLY JESUS'));
await admin.locator('#close').click();
await admin.locator('#clear-filters').click();
await admin.locator('#search').fill('Aaron Boison');
assert.equal(await admin.locator('tbody tr').count(),1);

const privacy=await context.newPage();
watch(privacy);
await privacy.goto(BASE,{waitUntil:'networkidle'});
assert(await privacy.evaluate(()=>{const event=new Event('contextmenu',{bubbles:true,cancelable:true});return !document.dispatchEvent(event)}));
await privacy.evaluate(()=>{window.dispatchEvent(new Event('blur'));window.dispatchEvent(new Event('focus'));document.dispatchEvent(new Event('visibilitychange'))});
await privacy.waitForTimeout(100);
assert.equal(await privacy.locator('.privacy-shield').count(),0);
assert.equal(await privacy.locator('body').evaluate(el=>el.classList.contains('privacy-hidden')),false);

const mobile=await context.newPage();
watch(mobile);
await mobile.setViewportSize({width:390,height:844});
await mobile.goto(BASE,{waitUntil:'networkidle'});
assert(await mobile.getByRole('heading',{name:'D.R.O.G.S'}).isVisible());
assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
await mobile.screenshot({path:`${OUT}/mobile-gate.png`,fullPage:true});

const idle=await context.newPage();
watch(idle);
await idle.clock.install();
await idle.goto(BASE,{waitUntil:'networkidle'});
await enterPortal(idle);
await idle.locator('#code').fill('B4');
await idle.getByRole('button',{name:'Continue'}).click();
await idle.clock.fastForward(29*60*1000);
assert(await idle.locator('.identity').isVisible());
await idle.locator('.identity h2').click();
await idle.clock.fastForward(29*60*1000);
assert(await idle.locator('.identity').isVisible());
await idle.clock.fastForward(61*1000);
assert(await idle.locator('#entry-code').isVisible());
await idle.goBack();
assert(await idle.locator('#entry-code').isVisible());
await idle.goto(`${BASE}/admin/`,{waitUntil:'networkidle'});
await idle.locator('#pin').fill('1234');
await idle.getByRole('button',{name:'Enter D.R.O.G.S Office'}).click();
await idle.locator('.portrait-card').first().click();
await idle.clock.fastForward(30*60*1000+1);
assert(await idle.locator('#pin').isVisible());
assert.equal(await idle.locator('.record-modal').count(),0);
assert.equal(errors.length,0,errors.join('\n'));
console.log('Browser QA passed: password gate, B/P codes, history navigation, optional declaration, proof upload, receipt, denomination identity, full-screen admin records, privacy controls, and mobile layout.');
console.log(OUT);
await browser.close();
