import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { createRequire } from 'node:module';

const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const BASE='http://127.0.0.1:4198';
const OUT='/tmp/drogs-qa';
await mkdir(OUT,{recursive:true});

const launchOptions={headless:true};
if(process.env.PLAYWRIGHT_EXECUTABLE_PATH)launchOptions.executablePath=process.env.PLAYWRIGHT_EXECUTABLE_PATH;
const browser=await chromium.launch(launchOptions);
const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});
const errors=[];
const watch=page=>{page.on('console',msg=>{if(msg.type()==='error')errors.push(`console: ${msg.text()}`)});page.on('pageerror',error=>errors.push(`page: ${error}`))};
const enterPortal=async page=>{await page.locator('#entry-code').fill('1234');await page.getByRole('button',{name:'Enter'}).click();await page.locator('#code').waitFor()};

const page=await context.newPage();
watch(page);
await page.goto(BASE,{waitUntil:'networkidle'});
await page.evaluate(()=>{localStorage.clear();sessionStorage.clear()});
await page.reload({waitUntil:'networkidle'});
assert(await page.getByRole('heading',{name:'D.R.O.G.S'}).isVisible());
assert.equal(await page.locator('[data-role]').count(),0);
assert.equal(await page.locator('.privacy-shield').count(),0);
await page.locator('#entry-code').fill('1111');
await page.getByRole('button',{name:'Enter'}).click();
assert((await page.locator('#entry-error').textContent()).includes('not correct'));
await enterPortal(page);
assert.equal(await page.locator('[data-role]').count(),0);
assert.equal(await page.locator('#code').getAttribute('placeholder'),'Enter your code here');
assert.equal(await page.locator('.hero p, .hero .eyebrow').count(),0);
assert(await page.locator('.hero .gate-logo').isVisible());
await page.locator('.gate-logo').evaluate(img=>img.decode());
await page.locator('#code').focus();
assert.equal(await page.locator('#code').evaluate(el=>getComputedStyle(el).outlineStyle),'none');
assert.equal(await page.locator('.access-card').evaluate(el=>getComputedStyle(el).outlineStyle),'solid');
await page.screenshot({path:OUT+'/home-focus.png',fullPage:true});
assert.equal(await page.locator('body').textContent().then(x=>new RegExp(['rene','wal'].join(''),'i').test(x)),false);
assert.equal(await page.evaluate(()=>document.documentElement.dataset.captureProtection),'limited');

await page.locator('#code').fill('B999');
await page.getByRole('button',{name:'Continue'}).click();
assert((await page.locator('#access-error').textContent()).includes('could not find'));
await page.locator('#code').fill('B4');
await page.getByRole('button',{name:'Continue'}).click();
assert((await page.locator('.topline h1').textContent()).includes('Adelaide Heward-Mills'));
assert.equal(await page.locator('.identity-copy h2').textContent(),'Adelaide Heward-Mills');
assert((await page.locator('.affiliation').textContent()).includes('UD-OLGC'));
assert.equal(await page.locator('.profile-title').textContent(),'Episcopal Sister');
assert(await page.locator('.profile-portrait').getAttribute('src'));
assert.equal(await page.locator('.portrait-watermark').count(),0);
assert.equal(await page.locator('.organization-name').textContent(),'UD-OLGC');
assert.equal(await page.locator('.denomination-name').textContent(),'QODESH CITY CHURCHES');
assert.equal(/International|code 4/i.test(await page.locator('.identity').textContent()),false);
await page.locator('.profile-portrait').evaluate(img=>img.decode());
await page.locator('.denomination-logo').evaluate(img=>img.decode());
await page.screenshot({path:`${OUT}/public-profile.png`,fullPage:true});

await page.goBack();
await page.locator('#code').waitFor();
assert.equal(await page.locator('.privacy-shield').count(),0);
assert.equal(await page.locator('body').evaluate(el=>el.classList.contains('privacy-hidden')),false);
await page.goForward();
await page.locator('.identity').waitFor();

await page.getByRole('button',{name:/Fill annual declaration/}).click();
await page.getByRole('heading',{name:'Your annual declaration'}).waitFor();
await page.getByRole('button',{name:/Continue to payment/}).click();
await page.getByRole('heading',{name:'Complete your annual commitment.'}).waitFor();
assert.equal(await page.locator('.payment-app').count(),17);
assert.equal(await page.getByRole('link',{name:'Open Wise'}).getAttribute('href'),'https://wise.com/send-money');
assert((await page.locator('.transfer-heading h2').textContent()).includes('053 042 9589'));
await page.getByRole('button',{name:/Submit payment proof/}).click();
assert((await page.locator('#proof-error').textContent()).includes('Upload'));
await page.locator('#proof').setInputFiles('/Users/joshuagbafa/Documents/Codex/pastoral-renewal/assets/mitre-transparent.png');
await page.locator('#proof-preview.ready').waitFor();
await page.getByRole('button',{name:'Bank transfer',exact:true}).click();
assert(await page.locator('#bank-details').isVisible());
assert.equal(await page.locator('#momo-details').isVisible(),false);
assert.equal(await page.evaluate(()=>FLOW_BANK_ACCOUNTS.length),1);
assert((await page.locator('#bank-details').textContent()).includes('0871081972'));
assert((await page.locator('#bank-details').textContent()).includes('Absa Bank Ghana Ltd'));
assert((await page.locator('#bank-details').textContent()).includes('BARCGHAC'));
assert((await page.locator('#bank-details').textContent()).includes('030164'));
await page.getByRole('button',{name:'Copy account number',exact:true}).click();
assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'0871081972');
await page.getByRole('button',{name:'Copy sort code',exact:true}).click();
assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'030164');
await page.getByRole('button',{name:'Mobile money',exact:true}).click();
assert(await page.locator('#momo-details').isVisible());
assert(await page.locator('#proof-preview.ready').isVisible());
await page.getByRole('button',{name:'Bank transfer',exact:true}).click();
await page.screenshot({path:`${OUT}/payment-proof.png`,fullPage:true});
await page.setViewportSize({width:390,height:844});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.locator('#bank-details').scrollIntoViewIfNeeded();
await page.waitForTimeout(350);
await page.locator('#bank-details').screenshot({path:OUT+'/bank-mobile.png'});
await page.setViewportSize({width:1440,height:1000});
await page.getByRole('button',{name:/Submit payment proof/}).click();
await page.getByText('Preparing your confirmation…').waitFor();
await page.getByRole('heading',{name:'Thank you, Adelaide Heward-Mills.'}).waitFor();
assert(await page.getByText('Your response is being reviewed by the D.R.O.G.S Office.').isVisible());
assert.equal(await page.getByRole('button',{name:'Print receipt'}).count(),0);
assert.equal(await page.getByText('Receipt number').count(),0);
assert.equal(await page.locator('.receipt-lines').count(),0);
assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('drogs-2027'))['bishop:4'].paymentMethod),'Bank transfer — Ghana');
await page.setViewportSize({width:390,height:844});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:OUT+'/confirmation-mobile.png',fullPage:true});
await page.setViewportSize({width:1440,height:1000});
const logoFit=await page.locator('.receipt-logo').evaluate(el=>({fit:getComputedStyle(el).objectFit,w:el.clientWidth,h:el.clientHeight,nw:el.naturalWidth,nh:el.naturalHeight}));
assert.equal(logoFit.fit,'contain');
assert(logoFit.w>0&&logoFit.h>0&&logoFit.nw>0&&logoFit.nh>0);
await page.screenshot({path:`${OUT}/receipt.png`,fullPage:true});

await page.getByRole('button',{name:'Return to record'}).click();
await page.getByRole('button',{name:'Sign out',exact:true}).click();
await page.locator('#entry-code').waitFor();
await page.goBack();
assert(await page.locator('#entry-code').isVisible());
await enterPortal(page);

await page.locator('#code').fill('P1');
await page.getByRole('button',{name:'Continue'}).click();
assert((await page.locator('.topline h1').textContent()).includes('Aaron Boison'));
assert((await page.locator('.affiliation').textContent()).includes('UD-OLGC'));
assert.equal(await page.locator('.denomination-logo').count(),1);
await page.screenshot({path:`${OUT}/pastor-profile.png`,fullPage:true});
await page.getByRole('button',{name:/Fill annual declaration/}).click();
await page.locator('#declaration-form').waitFor();
assert.equal(await page.locator('.qno').filter({hasText:'10'}).count(),1);
assert.equal(await page.locator('#pastorCalling').count(),1);
assert.equal(await page.locator('input[name="standing"]').count(),0);
assert.equal(await page.evaluate(()=>PASTOR_QUESTIONS.length),10);
await page.locator('#pastorCalling').fill('I remain committed to pastoral service.');
await page.getByLabel('Weekly',{exact:true}).check();
await page.getByRole('button',{name:/Continue to payment/}).click();
await page.locator('#bank-details').waitFor({state:'attached'});
assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('drogs-2027'))['pastor:1'].responses.pastorCalling),'I remain committed to pastoral service.');
await page.evaluate(()=>location.hash='declaration');
await page.locator('#pastorCalling').waitFor();
assert.equal(await page.locator('#pastorCalling').inputValue(),'I remain committed to pastoral service.');
await page.screenshot({path:OUT+'/pastor-questions.png',fullPage:true});
assert((await page.locator('.question').filter({has:page.locator('input[name="intention"]')}).locator('.qno').textContent()).includes('10'));
await page.getByLabel('I wish to resign',{exact:true}).check();
await page.getByRole('button',{name:'Submit response'}).click();
await page.getByText('Preparing your confirmation…').waitFor();
await page.getByRole('heading',{name:'Thank you, Aaron Boison.'}).waitFor();
assert.equal(await page.locator('.payment-app').count(),0);
await page.evaluate(()=>location.hash='payment');
await page.getByRole('heading',{name:'Thank you, Aaron Boison.'}).waitFor();
assert.equal(await page.locator('.payment-app').count(),0);


const admin=await context.newPage();
watch(admin);
await admin.goto(`${BASE}/admin/`,{waitUntil:'networkidle'});
assert.equal(await admin.evaluate(()=>document.documentElement.dataset.captureProtection),'limited');
await admin.locator('#pin').fill('1111');
await admin.getByRole('button',{name:'Enter D.R.O.G.S Office'}).click();
assert((await admin.locator('#error').textContent()).includes('not correct'));
await admin.locator('#pin').fill('1234');
await admin.getByRole('button',{name:'Enter D.R.O.G.S Office'}).click();
assert(await admin.getByRole('heading',{name:'D.R.O.G.S Office'}).isVisible());

assert.equal(await admin.locator('.portrait-card').count(),await admin.evaluate(()=>BISHOPS.length));
assert.equal(await admin.locator('#sort').count(),0);
assert(await admin.locator('.metrics .metric span').first().evaluate(el=>parseFloat(getComputedStyle(el).fontSize)>=16));
assert(await admin.locator('.metrics .metric strong').first().evaluate(el=>parseFloat(getComputedStyle(el).fontSize)>=44));
assert.equal(await admin.locator('.card-logo').count(),0);
assert.equal(await admin.locator('.card-photo').first().evaluate(img=>getComputedStyle(img).objectFit),'contain');
assert.equal(await admin.locator('.metric[data-filter="paid"] strong').textContent(),'1');
await admin.evaluate(()=>{
 const saved=JSON.parse(localStorage.getItem('drogs-2027')||'{}');
 saved['pastor:36']={status:'submitted',submittedAt:'2026-09-20T10:15:00.000Z',updatedAt:'2030-01-01T00:00:00.000Z',paid:false,review:'Ready for review',responses:{intention:'I wish to continue'}};
 localStorage.setItem('drogs-2027',JSON.stringify(saved));
});
await admin.getByRole('button',{name:'Submissions',exact:true}).click();
assert(await admin.getByRole('heading',{name:'Submissions',exact:true}).isVisible());
const timestamps=await admin.locator('.submission-table time').evaluateAll(elements=>elements.map(el=>Date.parse(el.dateTime)));
assert(timestamps.every((value,index)=>index===0||timestamps[index-1]>=value));
await admin.locator('[data-submission-role="pastor"]').click();
const submittedPastor=admin.locator('[data-submission-code="36"]');
assert.equal(await submittedPastor.locator('time').textContent(),'20 Sept 2026, 10:15');
await submittedPastor.getByRole('button').click();
assert.equal(await admin.locator('.record-title h2').textContent(),'Aboagye Blankson');
assert.equal(await admin.locator('.record-person-title').textContent(),'Pastor');
await admin.getByRole('button',{name:'Close record',exact:true}).click();
await admin.locator('#submission-search').fill('no-match-person');
assert((await admin.locator('.empty').textContent()).includes('No submissions match'));
await admin.locator('#submission-search').fill('');
await admin.getByRole('button',{name:'Resignations',exact:true}).click();
assert(await admin.getByRole('heading',{name:'Resignation requests',exact:true}).isVisible());
assert.equal(await admin.locator('.submission-table tbody tr').count(),1);
assert((await admin.locator('.submission-table tbody').textContent()).includes('Aaron Boison'));
assert((await admin.locator('.submission-table tbody').textContent()).includes('Not required'));
await admin.locator('[data-submission-role="bishop"]').click();
assert.equal(await admin.locator('.submission-table tbody tr').count(),0);
await admin.locator('[data-submission-role="all"]').click();
await admin.screenshot({path:OUT+'/admin-resignations.png',fullPage:true});
await admin.setViewportSize({width:390,height:844});
assert(await admin.locator('#submissions').isVisible());
assert(await admin.locator('#resignations').isVisible());
assert(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await admin.screenshot({path:OUT+'/admin-resignations-mobile.png',fullPage:true});
await admin.setViewportSize({width:1440,height:1000});
await admin.getByRole('button',{name:'Directory',exact:true}).click();
await admin.locator('[data-role="bishop"]').click();
await admin.locator('#search').pressSequentially('Adelaide');
assert.equal(await admin.locator('#search').inputValue(),'Adelaide');
assert.equal(await admin.locator('.portrait-card').count(),1);
await admin.locator('.portrait-card').click();
assert(await admin.locator('.record-modal').isVisible());
assert.equal(await admin.locator('.record-title h2').textContent(),'Adelaide Heward-Mills');
assert.equal(await admin.locator('.record-person-title').textContent(),'Episcopal Sister');
assert(await admin.locator('.admin-proof img').isVisible());
await admin.keyboard.press('Escape');
await admin.locator('#search').fill('Kiki');
await admin.locator('.portrait-card').click();
await admin.locator('.record-logo').evaluate(img=>img.decode());
assert(await admin.locator('.record-photo').getAttribute('src'));
assert.equal(await admin.locator('.record-photo').evaluate(img=>getComputedStyle(img).objectFit),'contain');
assert.equal(await admin.locator('.record-country').textContent(),await admin.evaluate(()=>{const p=BISHOPS.find(p=>p.name==='Kiki Heward-Mills');return p.region&&p.region!=='International'?p.region:'Country not recorded'}));
assert.equal(await admin.locator('.record-organization').count(),0);
await admin.screenshot({path:OUT+'/admin-record.png'});
await admin.locator('#browse-denomination').click();
assert(await admin.locator('.denomination-heading h2').isVisible());
assert(await admin.locator('[data-directory-role="pastor"]').isVisible());
const selectedDenomination=await admin.locator('.denomination-heading h2').textContent();
await admin.locator('[data-directory-role="pastor"]').click();
assert.equal(await admin.locator('.denomination-heading h2').textContent(),selectedDenomination);
await admin.locator('[data-directory-role="bishop"]').click();
assert.equal(await admin.locator('.record-modal').count(),0);
assert(await admin.locator('.portrait-card').count()>0);
await admin.locator('#clear-filters').click();
await admin.getByRole('button',{name:'Organization',exact:true}).click();
await admin.locator('[data-option="UD-OLGC"]').check();
const udCount=await admin.locator('.portrait-card').count();
assert.equal(udCount,await admin.evaluate(()=>BISHOPS.filter(p=>p.organization==='UD-OLGC').length));
await admin.locator('[data-option="UO-FLC190"]').check();
assert.equal(await admin.locator('.portrait-card').count(),await admin.evaluate(()=>BISHOPS.length));
await admin.locator('#done-filter').click();
await admin.locator('#clear-filters').click();
await admin.getByRole('button',{name:'Hide sidebar',exact:true}).click();
assert(await admin.locator('.shell').evaluate(el=>el.classList.contains('sidebar-collapsed')));
await admin.getByRole('button',{name:'Show sidebar',exact:true}).click();
assert((await admin.locator('.organization-counts').textContent()).includes('UD:'));
await admin.getByRole('button',{name:'Groups',exact:true}).click();
await admin.locator('[data-option="UI — United Islands"]').check();
assert(await admin.locator('.portrait-card').count()>0);
await admin.locator('#done-filter').click();
await admin.locator('#clear-filters').click();
await admin.screenshot({path:OUT+'/admin-directory.png'});
await admin.getByRole('button',{name:'List view',exact:true}).click();
assert.equal(await admin.locator('tbody tr').count(),await admin.evaluate(()=>BISHOPS.length));
assert(await admin.getByRole('columnheader',{name:'Title',exact:true}).isVisible());
assert(await admin.getByRole('columnheader',{name:'Country',exact:true}).isVisible());
assert.equal(await admin.getByRole('columnheader',{name:'Country / branch'}).count(),0);
await admin.locator('[data-role="pastor"]').click();
assert.equal(await admin.locator('tbody tr').count(),await admin.evaluate(()=>PASTORS.length));
await admin.getByRole('button',{name:'Groups',exact:true}).click();
await admin.locator('[data-option="FL OJ: ONLY JESUS"]').check();
assert(await admin.locator('tbody tr').count()>0);
await admin.locator('#done-filter').click();
await admin.locator('tbody tr').first().click();
assert((await admin.locator('.fact-grid').textContent()).includes('FL OJ: ONLY JESUS'));
await admin.locator('#close').click();
await admin.locator('#clear-filters').click();
assert.equal(await admin.locator('[data-filter="resignation"] strong').textContent(),'1');
await admin.locator('[data-filter="resignation"]').click();
assert.equal(await admin.locator('tbody tr').count(),1);
assert((await admin.locator('tbody tr').textContent()).includes('Aaron Boison'));
assert((await admin.locator('tbody tr').textContent()).includes('Not required'));
await admin.locator('#clear-filters').click();
await admin.locator('#search').fill('Aaron Boison');
assert.equal(await admin.locator('tbody tr').count(),1);

const privacy=await context.newPage();
watch(privacy);
await privacy.goto(BASE,{waitUntil:'networkidle'});
assert(await privacy.evaluate(()=>{const event=new Event('contextmenu',{bubbles:true,cancelable:true});return !document.dispatchEvent(event)}));
await privacy.evaluate(()=>{window.dispatchEvent(new Event('blur'));window.dispatchEvent(new Event('focus'));document.dispatchEvent(new Event('visibilitychange'))});
await privacy.waitForTimeout(100);
assert.equal(await privacy.locator('.privacy-shield').count(),0);
assert.equal(await privacy.locator('body').evaluate(el=>el.classList.contains('privacy-hidden')),false);

const mobile=await context.newPage();
watch(mobile);
await mobile.setViewportSize({width:390,height:844});
await mobile.goto(BASE,{waitUntil:'networkidle'});
assert(await mobile.getByRole('heading',{name:'D.R.O.G.S'}).isVisible());
assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
await mobile.screenshot({path:`${OUT}/mobile-gate.png`,fullPage:true});

const idle=await context.newPage();
watch(idle);
await idle.clock.install();
await idle.goto(BASE,{waitUntil:'networkidle'});
await enterPortal(idle);
await idle.locator('#code').fill('B255');
await idle.getByRole('button',{name:'Continue'}).click();
assert.equal(await idle.locator('.identity h2').textContent(),'Aboagye Blankson');
assert.equal(await idle.locator('.profile-title').textContent(),'Pastor');
await idle.getByRole('button',{name:'Sign out',exact:true}).click();
await enterPortal(idle);
await idle.locator('#code').fill('P4884');
await idle.getByRole('button',{name:'Continue'}).click();
assert((await idle.locator('.identity h2').textContent()).includes('Henrietta'));
await idle.clock.fastForward(29*60*1000);
assert(await idle.locator('.identity').isVisible());
await idle.locator('.identity h2').click();
await idle.clock.fastForward(29*60*1000);
assert(await idle.locator('.identity').isVisible());
await idle.clock.fastForward(61*1000);
assert(await idle.locator('#entry-code').isVisible());
await idle.goBack();
assert(await idle.locator('#entry-code').isVisible());
await idle.goto(`${BASE}/admin/`,{waitUntil:'networkidle'});
await idle.locator('#pin').fill('1234');
await idle.getByRole('button',{name:'Enter D.R.O.G.S Office'}).click();
await idle.locator('.portrait-card').first().click();
await idle.clock.fastForward(30*60*1000+1);
assert(await idle.locator('#pin').isVisible());
assert.equal(await idle.locator('.record-modal').count(),0);
assert.equal(errors.length,0,errors.join('\n'));
console.log('Browser QA passed: password gate, B/P codes, history navigation, optional declaration, proof upload, receipt, denomination identity, full-screen admin records, privacy controls, and mobile layout.');
console.log(OUT);
await browser.close();
